# This is default jargon that you can use. Feel free to change it. See: https://boogi.netlify.app/editing/rich_content/abbreviations
'docs':
  name: docs
  long_name: inspektre docs
  description: Inspektre Documentation
